### ISSUE TITLE
Little bug in readme.md and request for open source checkpoint file

### ISSUE THREAD

**Issue by FuJingyun** [Jabb0/FastFlow3D#13]
Thanks for your excellent job and detailed tutorial！ I notice that there maybe a little bug in the readme.md, since there are double "offset_y" in **Architecture-Scene Encoder-4.Encode each point as 8D (pillarCenter_x, pillarCenter_y, pillarCenter_z, offset_x, _offset_y_, _offset_y_, feature_0, feature_1)** 
Moreover, will you kindly release the trained checkpoint file for the network? Sincerely looking forward to your reply！

**Comment by Jabb0** [comment]
Hi. Thanks! Glad you like the work.

Again sorry for the late reply.

You are absolutely right. This should be offset_z. I will change it thanks!

Unfortunaly, I don't have a trained checkpoint I can provide you with as they are stored on the university servers and I don't have access anymore.

**Comment by FuJingyun** [comment]
Very glad to receive your reply! Thanks anyway 👍
