### ISSUE TITLE
Question of the dataset

### ISSUE THREAD

**Issue by FuJingyun** [Jabb0/FastFlow3D#14]
Thank you again for this outstanding work! Here I have a question about the waymo dataset version you used. I notice that the waymo dataset download path you provided in the readme.md (https://console.cloud.google.com/storage/browser/waymo_open_dataset_scene_flow) is different from the dataset of any version on the official website of waymo dataset (now latest version is waymo 1.4.0). I would like to know what is the difference between the dataset used in this work and the datasets that are open for download in the official website. Sincerely looking forward to your reply!

**Comment by Jabb0** [comment]
Hi,

first of all sorry for the late reply.
Thanks for the interest in the repo!

Yes, the dataset is different. We used the dataset that is referenced in the paper by Jund et. al.
I don't know where the differences are. We assumed that at time of writing the necessary labels (the scene flow) were not present in the official dataset, as these labels are part of the paper's results. 
You could check if they are now.

**Comment by FuJingyun** [comment]
Thank you very much for your detailed reply!

I have another question and sincerely hope to get your answer. I notice that a WeightsAndBiases _config.yaml_ file is needed for visualization, and it is mentioned in the code comment that the _config.yaml_ file must be downloaded from Weights and Biases. Since I'm trying to visualize the point clouds locally (the local server in our university cannot connect to the Internet), I have no idea how to get this file. Do you have any suggestions or is there an example of this _config.yaml_ file available?

I really appreciate your help and look forward to your reply！

**Comment by Jabb0** [comment]
The config.yaml was our way of getting the parameters used for training, which we need again for visualization.
Such as grid size etc.

If you can train using weights and biases without internet connection, the config.yaml will be in the local WnB folder in the repo. I think it's called .wnb and each run has it's own subfolder.

Alternatively, you can rewrite the code to pass in the parameters that are taken from config.yaml from a different file. 
I can check later which parameters are necessary but it should be in the code.

**Comment by FuJingyun** [comment]
Thanks for your suggestion！ I now understand what this _config.yaml_ file does and I think I can try to rewrite the code then 👍
